version: '3.9'

networks:
  fptagsnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_SUBNET}/16
          gateway: ${NET_GATEWAY}

services:
  web:
    container_name: fptags-web
    image: webdevops/php-apache:alpine-php7
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./web:/app
    depends_on:
      - db
    networks:
      - fptagsnetwork

  db:
    container_name: fptags-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - ./db:/docker-entrypoint-initdb.d
        - fp-db:/home/vm-fp/mysql
    networks:
      fptagsnetwork:
        ipv4_address: ${NET_DBIP}

volumes:
  fp-db:
